<script setup lang="ts">
import { invoiceStatus, csv } from '../../../shared/domain'
const { invoices, load } = useInvoiceData(); const route = useRoute()
const search = ref(''); const status = ref('all'); const vendor = ref(''); const from = ref(''); const to = ref(''); const archived = ref(false); const page = ref(1); const busy = ref(true); const error = ref('')
const suppliers = computed(() => [...new Set(invoices.value.map(i => i.vendor).filter(Boolean))].sort())
const filtered = computed(() => invoices.value.filter(i => i.archived === archived.value && (!search.value || `${i.vendor} ${i.vendorAddress || ''} ${i.vendorTaxId || ''} ${i.number} ${i.notes} ${i.file?.name} ${(i.lineItems || []).map(item => item.description).join(' ')}`.toLowerCase().includes(search.value.toLowerCase())) && (!vendor.value || i.vendor === vendor.value) && (!from.value || i.date >= from.value) && (!to.value || !!i.date && i.date <= to.value) && (status.value === 'all' || status.value === 'Unpaid' && i.reviewed && i.payment === 'unpaid' || status.value === 'Needs review' && !i.reviewed || invoiceStatus(i) === status.value)))
const pages = computed(() => Math.max(1, Math.ceil(filtered.value.length / 15)))
const shown = computed(() => filtered.value.slice((page.value - 1) * 15, page.value * 15))
watch([search, status, vendor, from, to, archived], () => { page.value = 1 })
async function refresh() { busy.value = true; error.value = ''; try { await load() } catch (e: any) { error.value = e.message } finally { busy.value = false } }
function exportCsv() { const url = URL.createObjectURL(new Blob(['\uFEFF' + csv(filtered.value)], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'invoxa-invoices.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
function clear() { search.value = ''; status.value = 'all'; vendor.value = ''; from.value = ''; to.value = '' }
onMounted(refresh)
</script>
<template><div class="page-heading"><div><p class="eyebrow">PROCESSED SUPPLIER BILLS</p><h1>Invoices</h1><p>Search extracted details, review exceptions and keep payments up to date.</p></div><div class="button-row"><button class="button secondary" :disabled="!filtered.length" @click="exportCsv">Export CSV ↓</button><NuxtLink to="/upload" class="button">Process invoice ↑</NuxtLink></div></div><p v-if="route.query.saved" role="status" class="success-message">Invoice saved. Your records and overview are up to date.</p><p v-if="error" role="alert" class="error">{{ error }} <button class="text-link" @click="refresh">Retry</button></p><section class="panel"><div class="filters"><label class="search-field">Search<input v-model="search" type="search" placeholder="Supplier, GST ID, item or invoice number"></label><label>Status<select v-model="status"><option value="all">All statuses</option><option>Needs review</option><option>Unpaid</option><option>Overdue</option><option>Due today</option><option>Due soon</option><option>Paid</option><option>Processing</option><option>Extraction failed</option></select></label><label>Supplier<select v-model="vendor"><option value="">All suppliers</option><option v-for="supplier in suppliers" :key="supplier">{{ supplier }}</option></select></label><label>Invoice date from<input v-model="from" type="date"></label><label>Invoice date to<input v-model="to" type="date"></label></div><div class="section-heading"><div class="button-row"><button class="tab-button" :aria-pressed="!archived" @click="archived = false">Active</button><button class="tab-button" :aria-pressed="archived" @click="archived = true">Archived</button></div><span class="muted">{{ filtered.length }} results <button class="text-link" @click="clear">Clear filters</button></span></div><p v-if="from && to && from > to" class="warning">The start date is after the end date.</p><p v-if="busy" class="loading" role="status">Loading invoices…</p><InvoiceTable v-else :invoices="shown" /><div class="pagination"><button class="button secondary" :disabled="page <= 1" @click="page--">← Previous</button><span>Page {{ page }} of {{ pages }}</span><button class="button secondary" :disabled="page >= pages" @click="page++">Next →</button></div></section></template>
