<script setup lang="ts">
import type { Workspace, Invoice } from '../../shared/domain'
import { money, dateLabel } from '../../shared/domain'
const { account, load } = useAccount(); const api = useApi(); const config = useRuntimeConfig().public
const form = reactive({ name: account.value?.workspace?.name || '', reminders: account.value?.workspace?.reminders || false, reminderDays: account.value?.workspace?.reminderDays || 7 })
const busy = ref(false); const error = ref(''); const saved = ref(false); const preview = ref<{ enabled: boolean; recipient: string; invoices: Invoice[] } | null>(null)
async function save() { busy.value = true; error.value = ''; saved.value = false; try { await api<Workspace>('/workspace', { method: 'PATCH', body: { ...form, version: account.value?.workspace?.version } }); await load(); saved.value = true; preview.value = null } catch (e: any) { error.value = e.message } finally { busy.value = false } }
async function showPreview() { error.value = ''; try { preview.value = await api('/reminders/preview') } catch (e: any) { error.value = e.message } }
</script>
<template><div class="page-heading"><div><p class="eyebrow">YOUR BUSINESS</p><h1>Workspace settings</h1><p>Keep your business details and reminder preferences up to date.</p></div></div><form class="panel settings-panel" @submit.prevent="save"><h2>Business details</h2><label>Business name<input v-model="form.name" required minlength="2" maxlength="100"></label><p class="muted">Owner: {{ account?.user.email }}</p><hr><h2>Payment reminders</h2><label class="check-label"><input v-model="form.reminders" type="checkbox"><span>Email me a daily digest when invoices are overdue or coming due.</span></label><label>Include invoices due within<select v-model.number="form.reminderDays"><option :value="3">3 days</option><option :value="7">7 days</option><option :value="14">14 days</option><option :value="30">30 days</option></select></label><p class="form-intro">Sent to your account email. Paid, archived and unreviewed invoices are excluded. Disable the checkbox to stop future reminders.</p><p v-if="config.appMode === 'local'" class="warning">Local mode saves this preference and shows a preview. It does not send email.</p><p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="saved" class="success-message" role="status">Settings saved.</p><div class="form-actions"><button type="button" class="button secondary" @click="showPreview">Preview saved reminders</button><button class="button" :disabled="busy">{{ busy ? 'Saving…' : 'Save settings' }}</button></div></form><section v-if="preview" class="panel settings-panel"><h2>Today’s reminder preview</h2><p class="form-intro">{{ preview.enabled ? 'Reminders enabled' : 'Reminders currently disabled' }} · {{ preview.recipient }}</p><p v-if="!preview.invoices.length">No invoices qualify today.</p><div v-for="invoice in preview.invoices" :key="invoice.id" class="vendor-row"><NuxtLink :to="`/invoices/${invoice.id}`" class="text-link">{{ invoice.vendor }} · {{ invoice.number }}</NuxtLink><span>{{ money(invoice.total) }} · {{ dateLabel(invoice.due) }}</span></div></section></template>
